[tasks.preview]
description = 'Preview articles'
run = 'npx zenn preview'

[tasks.new-article]
description = 'Create new article'
# slug はファイル名になるので必須扱いにしておく
run = [
    'npx zenn new:article --slug {{arg(name="slug")}}',
    'mkdir ./images/{{arg(name="slug")}}'
]
alias = 'new'
