[tasks.preview]
description = 'Preview articles'
run = 'zenn preview'
alias = 'p'

[tasks.new-article]
description = 'Create new article'
# slug はファイル名になるので必須扱いにしておく
run = [
    'zenn new:article --slug {{arg(name="slug")}}',
    'mkdir ./images/{{arg(name="slug")}}'
]
alias = 'new'
